snapcraft.yaml corrected

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -107,14 +107,6 @@ parts:
     override-build: |
       # export PATH=/snap/bin:$PATH
 
-      # Find the actual electron build folder
-      ELECTRON_BUILD_DIR=$(find ./dist -maxdepth 1 -type d -name "*linux*unpacked*" | head -n 1)
-
-      if [ -z "$ELECTRON_BUILD_DIR" ]; then
-          echo "Error: Electron build folder not found!"
-          exit 1
-      fi
-
       # According to package.json (electron build section) the electron app tries to get frontend
       # from frontend/dist folder (relative to where package.json lies)
       mkdir -p $CRAFT_PART_BUILD/frontend/dist
@@ -123,6 +115,14 @@ parts:
       # Install and build
       npm install
       npm run build:electron
+
+      # Find the actual electron build folder
+      ELECTRON_BUILD_DIR=$(find ./dist -maxdepth 1 -type d -name "*linux*unpacked*" | head -n 1)
+
+      if [ -z "$ELECTRON_BUILD_DIR" ]; then
+          echo "Error: Electron build folder not found!"
+          exit 1
+      fi
 
       # Copy output to $SNAPCRAFT_PART_INSTALL
       mkdir -p $SNAPCRAFT_PART_INSTALL/electron
